import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const bangkokSongs = [
  {
    title: 'アンテナ39',
    krtitle: '안테나 39',
    artist: 'buzzG',
    krartist: '버즈지',
    slug: 'antena-39',
    videoId: 'Hf8eR5nqXgs',
    youtube: 'https://www.youtube.com/watch?v=Hf8eR5nqXgs',
    spotify: 'https://open.spotify.com/track/2OpqyFWD3xvn4U3TshBABj',
    thumbnail: 'https://i.ytimg.com/vi/Hf8eR5nqXgs/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'ラビットホール',
    krtitle: '래빗 홀',
    artist: 'DECO*27',
    krartist: '데코*27',
    slug: 'rabbit-hole',
    videoId: 'kdAya-tqbL4',
    youtube: 'https://www.youtube.com/watch?v=kdAya-tqbL4',
    spotify: 'https://open.spotify.com/track/7BWa3RUfn0HbYNEYZDJNRe',
    thumbnail: 'https://i.ytimg.com/vi/kdAya-tqbL4/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'アウンノビーツ',
    krtitle: '아운노비츠',
    artist: 'tsumiki',
    krartist: '츠미키',
    slug: 'aun-no-beats',
    videoId: 'lJGHGK_ifNg',
    youtube: 'https://www.youtube.com/watch?v=lJGHGK_ifNg',
    spotify: 'https://open.spotify.com/track/5eLzz4DdAb0d3E6c7IIK7M',
    thumbnail: 'https://i.ytimg.com/vi/lJGHGK_ifNg/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: '太陽系デスコ',
    krtitle: '태양계 디스코',
    artist: 'NayutalieN',
    krartist: '나유타리엔',
    slug: 'taiyokei-disco',
    videoId: 'mh7tLfhU5-Q',
    youtube: 'https://www.youtube.com/watch?v=mh7tLfhU5-Q',
    spotify: 'https://open.spotify.com/track/0WMh2F8J9vCMKLUaHVPbVl',
    thumbnail: 'https://i.ytimg.com/vi/mh7tLfhU5-Q/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: '群青讃歌',
    krtitle: '군청찬가',
    artist: 'Junky',
    krartist: '정키',
    slug: 'gunjou-sanka',
    videoId: '_lxyj6rKg0g',
    youtube: 'https://www.youtube.com/watch?v=_lxyj6rKg0g',
    spotify: 'https://open.spotify.com/track/19KtJkzH2OVzMwD66pVt6j',
    thumbnail: 'https://i.ytimg.com/vi/_lxyj6rKg0g/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'からくりピエロ',
    krtitle: '꼭두각시 피에로',
    artist: '40mP',
    krartist: '40mP',
    slug: 'karakuri-pierrot',
    videoId: 'GvlaNFV5RNo',
    youtube: 'https://www.youtube.com/watch?v=GvlaNFV5RNo',
    spotify: 'https://open.spotify.com/track/27LPKBIxe5fKCZtD5qNiY3',
    thumbnail: 'https://i.ytimg.com/vi/GvlaNFV5RNo/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: '命ばっかり',
    krtitle: '목숨만',
    artist: 'Threee',
    krartist: '스리',
    slug: 'inochi-bakkari',
    videoId: 'TIpA_FWWRfE',
    youtube: 'https://www.youtube.com/watch?v=TIpA_FWWRfE',
    spotify: 'https://open.spotify.com/track/6kcwSCiQzc7VlEoQg76KFL',
    thumbnail: 'https://i.ytimg.com/vi/TIpA_FWWRfE/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: '聖者の行進',
    krtitle: '성자의 행진',
    artist: 'Giga',
    krartist: '기가',
    slug: 'seija-no-koushin',
    videoId: 'Fkj0S3vv2Rw',
    youtube: 'https://www.youtube.com/watch?v=Fkj0S3vv2Rw',
    spotify: 'https://open.spotify.com/track/1BpcPqOx2B2IEMEDEusDLU',
    thumbnail: 'https://i.ytimg.com/vi/Fkj0S3vv2Rw/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: '愛して愛して愛して',
    krtitle: '사랑해 사랑해 사랑해',
    artist: 'Kikuo',
    krartist: '키쿠오',
    slug: 'aishite-aishite-aishite',
    videoId: '2bTL1MNTiME',
    youtube: 'https://www.youtube.com/watch?v=2bTL1MNTiME',
    spotify: 'https://open.spotify.com/track/1xRYrRHjQXfUAOzYH0BI3R',
    thumbnail: 'https://i.ytimg.com/vi/2bTL1MNTiME/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: '踊れオーケストラ',
    krtitle: '춤춰라 오케스트라',
    artist: 'Yuuyu-P',
    krartist: '유우유P',
    slug: 'odore-orchestra',
    videoId: 'cxlhYp1gBT4',
    youtube: 'https://www.youtube.com/watch?v=cxlhYp1gBT4',
    spotify: 'https://open.spotify.com/track/0xbwH3PqVXvyT38VIKiTaL',
    thumbnail: 'https://i.ytimg.com/vi/cxlhYp1gBT4/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'ナンセンス文学',
    krtitle: '넌센스 문학',
    artist: 'Eve',
    krartist: '이브',
    slug: 'nonsense-speaker',
    videoId: 'W5b7N_oTCWw',
    youtube: 'https://www.youtube.com/watch?v=W5b7N_oTCWw',
    spotify: 'https://open.spotify.com/track/2AqPmPmLDnONThyL6wO7fs',
    thumbnail: 'https://i.ytimg.com/vi/W5b7N_oTCWw/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'ロウワー',
    krtitle: '로워',
    artist: 'Twinfield',
    krartist: '트윈필드',
    slug: 'lower',
    videoId: 'tFWxkGjVMN0',
    youtube: 'https://www.youtube.com/watch?v=tFWxkGjVMN0',
    spotify: 'https://open.spotify.com/track/3QG5smTYKOYrZHXu58LkEL',
    thumbnail: 'https://i.ytimg.com/vi/tFWxkGjVMN0/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: '私のR',
    krtitle: '나의 R',
    artist: 'wotaku',
    krartist: '워타쿠',
    slug: 'watashi-no-r',
    videoId: 'lsp52PL3Y_I',
    youtube: 'https://www.youtube.com/watch?v=lsp52PL3Y_I',
    spotify: 'https://open.spotify.com/track/1QbpQqH4TfQrqjmJjlNL2f',
    thumbnail: 'https://i.ytimg.com/vi/lsp52PL3Y_I/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'こっち向いて Baby',
    krtitle: '이리 봐 Baby',
    artist: 'toa',
    krartist: '토아',
    slug: 'kocchi-muite-baby',
    videoId: 'CXddz37HMyY',
    youtube: 'https://www.youtube.com/watch?v=CXddz37HMyY',
    spotify: 'https://open.spotify.com/track/50DjWiJL3i3OgmZK0H5UF3',
    thumbnail: 'https://i.ytimg.com/vi/CXddz37HMyY/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'メテオ',
    krtitle: '메테오',
    artist: 'Agoaniki-P',
    krartist: '아고아니키P',
    slug: 'meteor',
    videoId: 'bHGqbBWC5nE',
    youtube: 'https://www.youtube.com/watch?v=bHGqbBWC5nE',
    spotify: 'https://open.spotify.com/track/3liFtOkBMXXm49M5YVL3Ho',
    thumbnail: 'https://i.ytimg.com/vi/bHGqbBWC5nE/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'ワールドイズマイン',
    krtitle: '월드 이즈 마인',
    artist: 'ryo',
    krartist: '료',
    slug: 'world-is-mine',
    videoId: 'EuJ6UR_pD5s',
    youtube: 'https://www.youtube.com/watch?v=EuJ6UR_pD5s',
    spotify: 'https://open.spotify.com/track/15i6Zyi3VnFYbUXEcQc58y',
    thumbnail: 'https://i.ytimg.com/vi/EuJ6UR_pD5s/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'Catch',
    krtitle: '캣치',
    artist: 'SAWTOWNE',
    krartist: '소타운',
    slug: 'getcha',
    videoId: 'C6QXtppHqiU',
    youtube: 'https://www.youtube.com/watch?v=C6QXtppHqiU',
    spotify: 'https://open.spotify.com/track/4KCHBZJBjVDhg0j7AqM2Po',
    thumbnail: 'https://i.ytimg.com/vi/C6QXtppHqiU/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: ['Getcha!'],
  },
  {
    title: '脱法ロック',
    krtitle: '탈법 로크',
    artist: 'Neru',
    krartist: '네루',
    slug: 'dappou-rock',
    videoId: 'p3WH1O3_zfA',
    youtube: 'https://www.youtube.com/watch?v=p3WH1O3_zfA',
    spotify: 'https://open.spotify.com/track/1kZ1lLokFhMNaJL3aH8vSq',
    thumbnail: 'https://i.ytimg.com/vi/p3WH1O3_zfA/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'ロミオとシンデレラ',
    krtitle: '로미오와 신데렐라',
    artist: 'doriko',
    krartist: '도리코',
    slug: 'romeo-to-cinderella',
    videoId: '6p-XMsbPxoI',
    youtube: 'https://www.youtube.com/watch?v=6p-XMsbPxoI',
    spotify: 'https://open.spotify.com/track/27fzC2u9eHmnxc0uiFJcmx',
    thumbnail: 'https://i.ytimg.com/vi/6p-XMsbPxoI/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: '地獄極楽',
    krtitle: '지옥극락',
    artist: 'sasakure.UK & DECO*27',
    krartist: '사사쿠레UK & 데코*27',
    slug: 'jigoku-gokuraku',
    videoId: '_lqL0aedVWU',
    youtube: 'https://www.youtube.com/watch?v=_lqL0aedVWU',
    spotify: 'https://open.spotify.com/track/6e0bP5SsMpWJyqQI2NgaC6',
    thumbnail: 'https://i.ytimg.com/vi/_lqL0aedVWU/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'All I\u2019m Asking for is Love',
    krtitle: '올 아임 애스킹 포 이즈 러브',
    artist: 'Yunosuke & CircusP',
    krartist: '유노스케 & 서커스P',
    slug: 'all-im-asking-for-is-love',
    videoId: 'LbkdL0vOIZQ',
    youtube: 'https://www.youtube.com/watch?v=LbkdL0vOIZQ',
    spotify: 'https://open.spotify.com/track/4WXCnTbEn6YcDwfgvJLfyN',
    thumbnail: 'https://i.ytimg.com/vi/LbkdL0vOIZQ/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'ローリンガール',
    krtitle: '롤링걸',
    artist: 'wowaka',
    krartist: '워와카',
    slug: 'rolling-girl',
    videoId: 'NIqm73xsias',
    youtube: 'https://www.youtube.com/watch?v=NIqm73xsias',
    spotify: 'https://open.spotify.com/track/1qfPfREL3H3AKgGOTqMjbC',
    thumbnail: 'https://i.ytimg.com/vi/NIqm73xsias/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'from Y to Y',
    krtitle: '프롬 와이 투 와이',
    artist: 'JimmyThumb-P',
    krartist: '지미썸P',
    slug: 'from-y-to-y',
    videoId: 'RCJlNgLrC4w',
    youtube: 'https://www.youtube.com/watch?v=RCJlNgLrC4w',
    spotify: 'https://open.spotify.com/track/3eDz9lwG9OxXWRzQdJdx7T',
    thumbnail: 'https://i.ytimg.com/vi/RCJlNgLrC4w/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'Tell Your World',
    krtitle: '텔 유어 월드',
    artist: 'kz (livetune)',
    krartist: 'kz (라이브튠)',
    slug: 'tell-your-world',
    videoId: 'PqJNc9KVIZE',
    youtube: 'https://www.youtube.com/watch?v=PqJNc9KVIZE',
    spotify: 'https://open.spotify.com/track/28wbHhv1XNZC9VgkxXvCQN',
    thumbnail: 'https://i.ytimg.com/vi/PqJNc9KVIZE/maxresdefault.jpg',
    part: ['MIKU'],
    anotherName: [],
  },
];

async function main() {
  console.log('Starting to add Bangkok songs...');

  for (const song of bangkokSongs) {
    try {
      const created = await prisma.song.create({
        data: song,
      });
      console.log(`✓ Added: ${song.krtitle} (${song.title}) - ${song.krartist}`);
    } catch (error) {
      console.error(`✗ Failed to add ${song.title}:`, error);
    }
  }

  console.log('\nDone! All Bangkok songs have been added.');
}

main()
  .catch((e) => {
    console.error('Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
