import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const bangkokSongs = [
  {
    title: 'Artifact',
    krtitle: '아티팩트',
    artist: 'buzzG',
    krartist: '버즈지',
    slug: 'artifact',
    videoId: 'UPL_viPDFSM',
    youtube: 'https://www.youtube.com/watch?v=UPL_viPDFSM',
    spotify: 'https://open.spotify.com/track/25a28jcbgjocfD2jWlZ1Ay',
    thumbnail: 'https://i.scdn.co/image/ab67616d00001e02e70f3d1abbf38c02352c4e65',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'ヴァンパイア',
    krtitle: '뱀파이어',
    artist: 'DECO*27',
    krartist: '데코*27',
    slug: 'vampire',
    videoId: 'e1xCOsgWG0M',
    youtube: 'https://www.youtube.com/watch?v=e1xCOsgWG0M',
    spotify: 'https://open.spotify.com/track/5Atjzvg5qZcWZhXwZkHqPO',
    thumbnail: 'https://i.scdn.co/image/ab67616d00001e02c18cabe59bf0c54d6a729669',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'カルチャ',
    krtitle: '컬쳐',
    artist: 'ツミキ',
    krartist: '츠미키',
    slug: 'culture',
    videoId: 'KAoY-tK1l0o',
    youtube: 'https://www.youtube.com/watch?v=KAoY-tK1l0o',
    spotify: 'https://open.spotify.com/track/0dt8ev3Jebpwk6Z1eNYJaS',
    thumbnail: 'https://i.scdn.co/image/ab67616d00001e02793cc1981eec7f485cbc5697',
    part: ['MIKU'],
    anotherName: ['컬처'],
  },
  {
    title: 'スイートマジック',
    krtitle: '스위트 매직',
    artist: 'Junky',
    krartist: '정키',
    slug: 'sweet-magic',
    videoId: 'wZ1gEDquuyQ',
    youtube: 'https://www.youtube.com/watch?v=wZ1gEDquuyQ',
    spotify: 'https://open.spotify.com/track/3UyiHKbiPinMJX8HnLrAZo',
    thumbnail: 'https://static.wikia.nocookie.net/vocaloid/images/2/23/Games_-_Project_DIVA_-_Sweet_Magic.jpg/revision/latest?cb=20221102055256',
    part: ['RIN'],
    anotherName: [],
  },
  {
    title: 'テレキャスタービーボーイ',
    krtitle: '텔레캐스터 비보이',
    artist: 'すりぃ',
    krartist: '스리',
    slug: 'telecaster-b-boy',
    videoId: 'i-DZukWFR64',
    youtube: 'https://www.youtube.com/watch?v=i-DZukWFR64',
    spotify: 'https://open.spotify.com/track/2rkSQrbwRoH82pA40rTQf3',
    thumbnail: 'https://static.wikia.nocookie.net/vocaloid/images/c/cb/Games_-_Project_SEKAI_-_Telecaster_B-Boy.png/revision/latest?cb=20220710101203',
    part: ['REN'],
    anotherName: [],
  },
  {
    title: '劣等上等',
    krtitle: '열등상등',
    artist: 'Giga',
    krartist: '기가',
    slug: 'rettou-joutou',
    videoId: 'oEkGC2HV7rc',
    youtube: 'https://www.youtube.com/watch?v=oEkGC2HV7rc',
    spotify: 'https://open.spotify.com/track/367IrkRR4wk5WtSL41rONn',
    thumbnail: 'https://static.wikia.nocookie.net/vocaloid/images/7/70/Games_-_Project_SEKAI_-_%E5%8A%B7%E7%AD%89%E4%B8%8A%E7%AD%89.png/revision/latest?cb=20220625151314',
    part: ['RIN', 'REN'],
    anotherName: [],
  },
  {
    title: '神っぽいな',
    krtitle: '신 같네',
    artist: 'ピノキオピー',
    krartist: '피노키오피',
    slug: 'god-ish',
    videoId: 'EHBFKhLUVig',
    youtube: 'https://www.youtube.com/watch?v=EHBFKhLUVig',
    spotify: 'https://open.spotify.com/track/206UWNKXURTnN4zf9vmXUV',
    thumbnail: 'https://static.wikia.nocookie.net/vocaloid/images/c/ca/God-ish_Pinocchio-P_%28single%29.png/revision/latest?cb=20230117043514',
    part: ['MIKU'],
    anotherName: ['카밋포이나', '카밋뽀이나'],
  },
  {
    title: 'ナイフ、ナイフ、ナイフ',
    krtitle: '나이프, 나이프, 나이프',
    artist: 'きくお',
    krartist: '키쿠오',
    slug: 'knife-knife-knife',
    videoId: 'h4WrL4wLp3M',
    youtube: 'https://www.youtube.com/watch?v=h4WrL4wLp3M',
    spotify: 'https://open.spotify.com/track/4HwiyW9d8fyoKWZ8fPsnqX',
    thumbnail: 'https://i.scdn.co/image/ab67616d00001e025ca2a3cb354a0c2fe81e8ec0',
    part: ['MIKU'],
    anotherName: ['🔪、🔪、🔪', '나이프 나이프 나이프'],
  },
  {
    title: '深海少女',
    krtitle: '심해소녀',
    artist: 'ゆうゆP',
    krartist: '유우유P',
    slug: 'shinkai-shoujo',
    videoId: '2CwBFr-Eoxg',
    youtube: 'https://www.youtube.com/watch?v=2CwBFr-Eoxg',
    spotify: 'https://open.spotify.com/track/5ymnEcBJonBJMSRRXIWM25',
    thumbnail: 'https://i.scdn.co/image/ab67616d0000b27319da7fce128382794082a226',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'レッドランドマーカー',
    krtitle: '레드 랜드 마커',
    artist: 'Twinfield',
    krartist: '트윈필드',
    slug: 'red-land-marker',
    videoId: 'DJfPFNLVVR8',
    youtube: 'https://www.youtube.com/watch?v=DJfPFNLVVR8',
    spotify: 'https://open.spotify.com/track/2Lfr5cRJW4kzlYpMT2fQN8',
    thumbnail: 'https://i.scdn.co/image/ab67616d00001e02a8c7ea3bccff25a6274cbfe9',
    part: ['MEIKO'],
    anotherName: [],
  },
  {
    title: 'リテラシー',
    krtitle: '리터러시',
    artist: 'wotaku',
    krartist: '워타쿠',
    slug: 'literacy',
    videoId: 'd3ZOnM1I17s',
    youtube: 'https://www.youtube.com/watch?v=d3ZOnM1I17s',
    spotify: 'https://open.spotify.com/track/0l43BkBXDlH51F5a1FqCjp',
    thumbnail: 'https://i.scdn.co/image/ab67616d00001e02b16ce2f75863be8556992e58',
    part: ['KAITO'],
    anotherName: [],
  },
  {
    title: 'on the rocks',
    krtitle: '온 더 락',
    artist: 'OSTER project',
    krartist: '오스터 프로젝트',
    slug: 'on-the-rocks',
    videoId: 'hk1L0ZV2bVc',
    youtube: 'https://www.youtube.com/watch?v=hk1L0ZV2bVc',
    spotify: 'https://open.spotify.com/track/5oUBjW4Bc69fcYBak14CyO',
    thumbnail: 'https://static.wikia.nocookie.net/vocaloid/images/e/ec/Games_-_Project_SEKAI_-_On_the_rocks.png/revision/latest?cb=20220726162332',
    part: ['MEIKO', 'KAITO'],
    anotherName: ['온 더 락스'],
  },
  {
    title: 'ツギハギスタッカート',
    krtitle: '누덕누덕 스타카토',
    artist: 'とあ',
    krartist: '토아',
    slug: 'tsugihagi-staccato',
    videoId: 'p2Irc9NPCtk',
    youtube: 'https://www.youtube.com/watch?v=p2Irc9NPCtk',
    spotify: 'https://open.spotify.com/track/0V7RxFamMkLN6tXR7S2t1W',
    thumbnail: 'https://static.wikia.nocookie.net/vocaloid/images/d/df/Games_-_Project_SEKAI_-_%E3%83%84%E3%82%AE%E3%83%8F%E3%82%AE%E3%82%B9%E3%82%BF%E3%83%83%E3%82%AB%E3%83%BC%E3%83%88.png/revision/latest?cb=20220708094901',
    part: ['MIKU'],
    anotherName: ['츠기하기 스타카토'],
  },
  {
    title: 'ダブルラリアット',
    krtitle: '더블 래리어트',
    artist: 'アゴアニキ',
    krartist: '아고아니키',
    slug: 'double-lariat',
    videoId: 'hC8KrIY8qT4',
    youtube: 'https://www.youtube.com/watch?v=hC8KrIY8qT4',
    spotify: 'https://open.spotify.com/track/3ZCA0UwO63EJAnstJ80pCN',
    thumbnail: 'https://static.wikia.nocookie.net/vocaloid/images/4/4b/Games_-_Project_SEKAI_-_%E3%83%80%E3%83%96%E3%83%AB%E3%83%A9%E3%83%AA%E3%82%A2%E3%83%83%E3%83%88.png/revision/latest?cb=20221003091250',
    part: ['LUKA'],
    anotherName: [],
  },
  {
    title: '愛Dee',
    krtitle: '아이Dee',
    artist: 'Mitchie M',
    krartist: '밋치M',
    slug: 'aidee',
    videoId: '8I0H1dXQxEo',
    youtube: 'https://www.youtube.com/watch?v=8I0H1dXQxEo',
    spotify: 'https://open.spotify.com/track/1MytGyxmiRweA6GmXsMJ3A',
    thumbnail: 'https://i1.sndcdn.com/artworks-000125082317-avcxuy-t1080x1080.jpg',
    part: ['MIKU', 'LUKA'],
    anotherName: ['아이디'],
  },
  {
    title: 'M@GICAL☆CURE! LOVE ♥ SHOT!',
    krtitle: '매지컬 큐어 러브 샷',
    artist: 'SAWTOWNE',
    krartist: '소타운',
    slug: 'magical-cure-love-shot',
    videoId: 'LaEgpNBt-bQ',
    youtube: 'https://www.youtube.com/watch?v=LaEgpNBt-bQ',
    spotify: 'https://open.spotify.com/track/63yoRZd5zl6Ah30hfDm97k',
    thumbnail: 'https://i.scdn.co/image/ab67616d00001e02a2f3d4936b6f398d90949081',
    part: ['MIKU'],
    anotherName: ['M@GICAL☆CURE! LOVE SHOT!', '미쿠미쿠빔', 'MAGICAL CURE! LOVE SHOT!', 'MAGICAL CURE LOVE SHOT', '매지컬 큐어! 러브 샷!'],
  },
  {
    title: 'Satisfaction',
    krtitle: '새티스팩션',
    artist: 'kz(livetune)',
    krartist: 'kz(라이브튠)',
    slug: 'satisfaction',
    videoId: '4h6n6Q4BLVs',
    youtube: 'https://www.youtube.com/watch?v=4h6n6Q4BLVs',
    spotify: 'https://open.spotify.com/track/3D4oFADIdzNln7HTdXMuuE',
    thumbnail: 'https://i.scdn.co/image/ab67616d00001e02db6a2b443194a73fd9fa7298',
    part: ['MIKU'],
    anotherName: ['새디스팩션'],
  },
  {
    title: 'shake it!',
    krtitle: '셰이크 잇',
    artist: 'emon(Tes.)',
    krartist: '에몬(Tes.)',
    slug: 'shake-it',
    videoId: 'WxexMGe83No',
    youtube: 'https://www.youtube.com/watch?v=WxexMGe83No',
    spotify: 'https://open.spotify.com/track/3Vpeg9gppDumSMsGmbKsYZ',
    thumbnail: 'https://static.wikia.nocookie.net/vocaloid/images/8/8d/Shake_it%21.png/revision/latest?cb=20170414095136',
    part: ['MIKU', 'RIN', 'REN'],
    anotherName: [],
  },
  {
    title: '39',
    krtitle: '39',
    artist: 'sasakure.UK x DECO*27',
    krartist: '사사쿠레UK x 데코*27',
    slug: '39',
    videoId: 'ecU_uJRzhfk',
    youtube: 'https://www.youtube.com/watch?v=ecU_uJRzhfk',
    spotify: 'https://open.spotify.com/track/3wmmuJJ1G9Ykkhp3NAqk8u',
    thumbnail: 'https://i.scdn.co/image/ab67616d00001e02eb7f14c455606d9170d2e7bb',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'Intergalactic Bound',
    krtitle: '인터갤럭틱 바운드',
    artist: 'Yunosuke & CircusP',
    krartist: '유노스케 & 서커스P',
    slug: 'intergalactic-bound',
    videoId: 'jsQXgDZIIrY',
    youtube: 'https://www.youtube.com/watch?v=jsQXgDZIIrY',
    spotify: 'https://open.spotify.com/track/25tNraNmMNwSEccFVcXxnu',
    thumbnail: 'https://i.scdn.co/image/ab67616d00001e0223e498c04c74bdcbcd842b7f',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'ローリンガール',
    krtitle: '롤링 걸',
    artist: 'wowaka',
    krartist: '워와카',
    slug: 'rolling-girl',
    videoId: 'vnw8zURAxkU',
    youtube: 'https://www.youtube.com/watch?v=vnw8zURAxkU',
    spotify: 'https://open.spotify.com/track/3CNptmi6HPZj6lgglUafW7',
    thumbnail: 'https://static.wikia.nocookie.net/vocaloid/images/b/b0/Rollingirl.jpg/revision/latest?cb=20200307050333',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'DECORATOR',
    krtitle: '데코레이터',
    artist: 'kz(livetune)',
    krartist: 'kz(라이브튠)',
    slug: 'decorator',
    videoId: 'zweVJrnE1uY',
    youtube: 'https://www.youtube.com/watch?v=zweVJrnE1uY',
    spotify: 'https://open.spotify.com/track/68cGngZvXl6qKGLH3joVpZ',
    thumbnail: 'https://static.wikia.nocookie.net/vocaloid/images/2/23/DECORATOR_EP.jpg/revision/latest?cb=20140307172934',
    part: ['MIKU'],
    anotherName: [],
  },
  {
    title: 'メルト',
    krtitle: '멜트',
    artist: 'ryo',
    krartist: '료',
    slug: 'melt',
    videoId: 'o1jAMSQyVPc',
    youtube: 'https://www.youtube.com/watch?v=o1jAMSQyVPc',
    spotify: 'https://open.spotify.com/track/6nWONiqCJwFxKKfAJSKaev',
    thumbnail: 'https://static.wikia.nocookie.net/vocaloid/images/e/e0/HatsuneMiku-Melt.jpg/revision/latest?cb=20091005152345',
    part: ['MIKU'],
    anotherName: [],
  },
];

async function main() {
  console.log('Starting to add Bangkok songs (correct version)...\n');

  for (const song of bangkokSongs) {
    try {
      const created = await prisma.song.create({
        data: song,
      });
      console.log(`✓ Added: ${song.krtitle} (${song.title}) - ${song.krartist}`);
    } catch (error) {
      console.error(`✗ Failed to add ${song.title}:`, error);
    }
  }

  console.log('\n✅ Done! All Bangkok songs have been added correctly.');
}

main()
  .catch((e) => {
    console.error('Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
